providers/openai/base.go

✨ feat: Azure OpenAI model name automatically removes dots.

---

common/model-ratio.go
controller/model.go
providers/openai/base.go
router/api-router.go
web/src/views/Channel/component/EditModal.js
web/src/views/Channel/component/NameLabel.js
web/src/views/Channel/type/Config.js
web/src/views/Dashboard/component/SupportModels.js
web/src/views/Dashboard/index.js

- 模型列表完善`OwnedBy`值返回
- 对渠道 模型下拉列表 进行分组
- 渠道 新增/修改 `填入渠道支持模型` 按钮支持自动填入当前选中渠道类型支持的模型
- 后台新增显示用户当前支持使用的模型
close #10

✨ feat: Optimize model list.

---

.gitignore
providers/baidu/chat.go
providers/baidu/type.go
providers/base/common.go
providers/xunfei/chat.go
providers/xunfei/type.go
types/chat.go

✨ feat: 更新模型支持

---

providers/azure/base.go
providers/openai/base.go
providers/providers.go

🐛 fix: custom channel error

---

controller/model.go
web/src/contexts/StatusContext.js
web/src/utils/api.js
web/src/utils/common.js
web/src/views/About/index.js
web/src/views/Authentication/AuthForms/ForgetPasswordForm.js
web/src/views/Authentication/AuthForms/ResetPasswordForm.js
web/src/views/Channel/component/EditModal.js
web/src/views/Channel/component/TableRow.js
web/src/views/Channel/index.js
web/src/views/Dashboard/index.js
web/src/views/Home/index.js
web/src/views/Log/index.js
web/src/views/Profile/component/EmailModal.js
web/src/views/Profile/index.js
web/src/views/Redemption/component/EditModal.js
web/src/views/Redemption/index.js
web/src/views/Setting/component/OperationSetting.js
web/src/views/Setting/component/OtherSetting.js
web/src/views/Setting/component/SystemSetting.js
web/src/views/Token/component/EditModal.js
web/src/views/Token/index.js
web/src/views/Topup/component/InviteCard.js
web/src/views/Topup/component/TopupCard.js
web/src/views/User/component/EditModal.js
web/src/views/User/index.js

- 修复自定义模型时，`OwnedBy`为空导致的排序问题
- 为web的api请求添加异常处理
- 修复了发送email时前端逻辑错误
close #34

Fix： 修复一些问题

---

providers/api2d/balance.go
providers/api2gpt/balance.go
providers/closeai/balance.go
providers/openai/balance.go
providers/openaisb/balance.go

🐛 fix: balance fail

---

common/requester/http_client.go
common/test/api.go
model/channel.go
providers/ali/base.go
providers/azure/base.go
providers/azure/image_generations.go
providers/azureSpeech/base.go
providers/baichuan/base.go
providers/baidu/base.go
providers/claude/base.go
providers/gemini/base.go
providers/openai/base.go
providers/palm/base.go
providers/tencent/base.go
providers/xunfei/base.go
providers/zhipu/base.go

- 修复代理无法删除的问题
- 修复使用代理后，代理池中的cilent未清除代理状态的bug
close #48

🐛 fix: proxy bug

---

common/requester/http_requester.go
common/requester/http_stream_reader.go
common/requester/ws_reader.go
common/requester/ws_requester.go
controller/relay-chat.go
controller/relay-completions.go
controller/relay-utils.go
providers/ali/chat.go
providers/baichuan/chat.go
providers/baidu/chat.go
providers/base/interface.go
providers/claude/chat.go
providers/gemini/chat.go
providers/minimax/chat.go
providers/openai/chat.go
providers/openai/completion.go
providers/palm/chat.go
providers/tencent/chat.go
providers/xunfei/chat.go
providers/zhipu/chat.go

🐛 fix: stream mode delay issue

---

controller/relay-utils.go
middleware/auth.go

🐛 fix: admin custom channel id failed

---

controller/analytics.go
controller/user.go
model/channel.go
model/common.go
model/log.go
model/redemption.go
model/user.go
router/api-router.go
web/src/menu-items/panel.js
web/src/routes/MainRoutes.js
web/src/ui-component/DateRangePicker.js
web/src/ui-component/cards/DataCard.js
web/src/ui-component/cards/Skeleton/DataCard.js
web/src/ui-component/chart/ApexCharts.js
web/src/utils/chart.js
web/src/views/Analytics/component/BubbleChard.js
web/src/views/Analytics/component/Overview.js
web/src/views/Analytics/component/Statistics.js
web/src/views/Analytics/index.js
web/src/views/Dashboard/index.js

添加 管理员统计 页面
新增 用户注册时间 字段。
由于 注册时间已经缺失，可以执行以下`SQL`将用户第一次产生日志的时间作为注册时间。
```
UPDATE users
SET created_time = (
SELECT MIN(created_at)
FROM logs
WHERE logs.user_id = users.id
);
```

✨ feat: add admin statistics

---

common/model-ratio.go
router/dashboard.go

查询余额接口支持跨域请求

---

common/constants.go
common/model-ratio.go
providers/moonshot/base.go
web/src/constants/ChannelConstants.js
web/src/views/Channel/type/Config.js

[moonshot](https://platform.moonshot.c)

✨ feat: support moonshot

---

providers/azure/base.go

✨ feat: support azure openai tts

---

controller/quota.go

🐛 fix: Model cost calculation error

---

common/constants.go
common/requester/http_client.go
common/requester/http_requester.go
common/requester/request_builder.go
providers/zhipu/chat.go

🐛 fix: glm-4v support base64 image

---

common/model-ratio.go
controller/model.go
go.mod
go.sum
model/channel.go
providers/ali/chat.go
providers/minimax/chat.go
providers/palm/chat.go
providers/tencent/chat.go
providers/xunfei/chat.go
providers/zhipu/base.go
providers/zhipu/chat.go
providers/zhipu/image_generations.go
providers/zhipu/type.go
web/src/views/Channel/component/EditModal.js
web/src/views/Channel/type/Config.js
web/src/views/Channel/type/Plugin.json

- 渠道支持设置插件
- 删除`zhipu`无效模型名称
- 修复一些问题

⚡️ feat: channel support plugin settings

---

common/constants.go
common/model-ratio.go
controller/model.go
providers/mistral/base.go
providers/mistral/chat.go
providers/mistral/embeddings.go
providers/mistral/type.go
providers/providers.go
web/src/constants/ChannelConstants.js
web/src/views/Channel/type/Config.js

✨ feat: support mistral

---

common/model-ratio.go
providers/baidu/base.go
providers/claude/base.go
providers/xunfei/chat.go
web/src/views/Channel/type/Config.js

✨ feat: complete some issues

---

README.en.md
README.md
common/constants.go
i18n/en.json
providers/ollama/base.go
providers/ollama/chat.go
providers/ollama/embeddings.go
providers/ollama/type.go
providers/providers.go
relay/util/type.go
web/src/constants/ChannelConstants.js
web/src/views/Channel/component/EditModal.js
web/src/views/Channel/type/Config.js
web/src/views/Channel/type/Plugin.json

支持[Ollama](https://github.com/ollama/ollama)。
支持配置使用`cloudflare Zero Trust`将服务暴露公网时，可以使用`Service Authentication` 中的`Token`认证

✨ feat:  support  Ollama

---

controller/channel-model.go
providers/base/common.go
providers/base/interface.go
providers/cohere/base.go
providers/cohere/model.go
providers/cohere/type.go
providers/deepseek/base.go
providers/gemini/base.go
providers/gemini/model.go
providers/gemini/type.go
providers/groq/base.go
providers/mistral/base.go
providers/mistral/model.go
providers/mistral/type.go
providers/openai/base.go
providers/openai/model.go
providers/openai/type.go
router/api-router.go
web/src/views/Channel/component/EditModal.js
web/src/views/Channel/type/Config.js

现已支持以下供应商自动获取模型：
- OpenAI
- 自定义渠道
- Gemini
- Deepseek
- Mistral
- Groq
- Cohere
close #183

✨ feat: Add support for retrieving model list from providers

---

.github/workflows/docker-image-en.yml
.github/workflows/docker-image.yml
web/src/constants/chatLinks.js
web/src/utils/common.js
web/src/views/Setting/component/ChatLinksDataGrid.js
web/src/views/Setting/component/OperationSetting.js

增加聊天链接排序功能

---

go.mod
go.sum
payment/gateway/alipay/payment.go
payment/gateway/alipay/type.go
payment/payment.go
web/src/views/Payment/type/Config.js

feat(增加支付宝支付功能): 增加支付宝支付功能（Preview）
增加支付宝当面付（扫码支付）和网页跳转支付功能

✨ feat: add Alipay payment

---

relay/relay_util/quota.go

🐛 fix: free models don't pre-quota consumption

---

web/src/views/Topup/component/TopupCard.js

🔖 chore: add pay button

---

go.mod
go.sum
payment/gateway/wxpay/client.go
payment/gateway/wxpay/payment.go
payment/gateway/wxpay/type.go
payment/payment.go
web/src/views/Payment/type/Config.js

✨ feat: add wechatPay

---

common/config/payment.go
common/recharge-discount.go
controller/misc.go
controller/order.go
model/option.go
model/order.go
web/src/views/Payment/Order.js
web/src/views/Payment/component/OrderTableRow.js
web/src/views/Payment/component/OrderTableToolBar.js
web/src/views/Setting/component/OperationSetting.js
web/src/views/Setting/component/OtherSetting.js
web/src/views/Topup/component/TopupCard.js

🔖 chore:  Add fixed pricing settings and discount

---

model/log.go

🐛 fix: Log error

---

web/src/views/Pricing/component/CheckUpdates.js

🔖 chore: add more formats

---

model/user.go
web/src/views/User/index.js

🔖 chore: Add user groups as query condition

---

prices.json

claude sonnet原本价格不对, 现调整, 并新增新claude-3-5-sonnet-20240620的价格
官方文档: [https://docs.anthropic.com/en/docs/about-claude/models#model-comparison](https://docs.anthropic.com/en/docs/about-claude/models#model-comparison)

🔧 chore: Update prices.json

---

.github/workflows/docker-image.yml

🔖 chore: Update Node.js version to 22.4.1 in docker-image workflow

---

prices.json

添加`gpt-4o-2024-08-06`价格

---

prices.json

add chatgpt-4o-latest price

---

controller/channel-model.go

部分中转模型列表里有重复, 会无法插入, 这里做一下删除

---

common/oidc/oidc.go
controller/oidc.go
router/api-router.go
web/src/utils/common.js

1. 修复OIDC配置后需要重启系统才生效 - 系统启动初始化一次，并且每次调用会判断配置是否正确加载，配置没初始化就先初始化 
2. 修复一个拼写错误

fix(OIDC登录): 修复一些问题

---

common/config/constants.go
providers/github/base.go
providers/providers.go
relay/relay_util/type.go
web/src/constants/ChannelConstants.js
web/src/views/Channel/type/Config.js

feat(渠道): 增加Github渠道

---

common/storage/drives/s3.go
common/storage/storage.go
config.example.yaml
go.mod
go.sum

feat(storage): 增加S3协议存储

---

controller/order.go
go.mod
go.sum
payment/gateway/stripe/payment.go
payment/gateway/stripe/type.go
payment/payment.go
payment/service.go
payment/types/types.go
web/src/views/Payment/type/Config.js

feat(pay): 增加Stripe支付

---

controller/payment.go
go.mod
go.sum
gowatch.yml
payment/gateway/alipay/payment.go
payment/gateway/epay/payment.go
payment/gateway/stripe/payment.go
payment/gateway/wxpay/payment.go
payment/payment.go
payment/service.go
web/pnpm-lock.yaml
web/src/views/Payment/type/Config.js

feat(pay): 增加Stripe支付创建过程中自动创建Stripe webhook，不需要手动创建
close #371 

feat(pay): 增加Stripe支付创建过程中自动创建Stripe webhook，不需要手动创建

---

.editorconfig
.gitignore
.golangci.yml
Taskfile.yml
common/config/constants.go
hack/scripts/genui.sh
makefile

- Add a new `.editorconfig` file for consistent coding styles
- Update `.gitignore` to exclude the `_output` directory
- Introduce a new `.golangci.yml` file to configure linters for the project
- Create a `Taskfile.yml` for task management and automation scripts
- Add variables and tasks for building and running the application in `Taskfile.yml`
- Declare new variables for build information in `common/config/constants.go`
- Introduce a new script `genui.sh` for building the front-end assets

chore: add configuration files and automate build tasks

---

web/src/views/Channel/component/EditModal.jsx

添加模型名称复制功能

---

providers/bedrock/category/base.go
providers/vertexai/category/claude.go

feat(Provider aws & google cloud): add claude-3-5-sonnet-20241022-v2:0

---

web/src/views/Playground/index.jsx

在只有一个Playground的情况下隐藏tab选择
close #235

feat(playground): 优化prayground显示方式

---

web/src/views/Pricing/index.jsx

fix(pricing): 修复模型价格无法新增的问题

---

providers/azure/base.go
providers/azure/model.go
providers/azure/type.go
providers/openai/base.go
web/src/views/Channel/type/Config.js

增加azure渠道模型部署列表获取功能，方便快速新建或者更新azure渠道

feat(渠道管理): 增加azure渠道模型部署列表获取功能

---

providers/moonshot/balance.go

feat(渠道管理): 增加moonshot渠道余额查询功能

---

common/notify/channel/wecom.go
common/notify/notifier.go
config.example.yaml

feat(notify): add wecom webhook support

---

providers/ali/chat.go

feat(ali): 支持QwQ模型思维链

---

providers/ali/base.go

fix Qwen2.5 VL models

---

docs/use/prices_update.md

- replace plain links with markdown-style links for better readability
- add descriptions for automated synchronization scripts
- clarify supplier ID mapping requirements and compatibility details

📝 docs(prices_update): update links and descriptions in pricing guide

---

web/src/views/Channel/component/TableToolBar.jsx
web/src/views/Log/component/TableToolBar.jsx

渠道页日志页组件对齐

---

model/option.go
web/src/i18n/locales/zh_CN.json
web/src/layout/MainLayout/Sidebar/index.jsx
web/src/layout/MainLayout/index.jsx
web/src/themes/index.js
web/src/ui-component/AdminContainer.js
web/src/views/Channel/index.jsx
web/src/views/Dashboard/component/InviteCard.jsx
web/src/views/Dashboard/component/QuotaLogWeek.jsx
web/src/views/Dashboard/component/StatisticalLineChartCard.jsx
web/src/views/Dashboard/index.jsx
web/src/views/Log/index.jsx
web/src/views/Midjourney/index.jsx
web/src/views/ModelOwnedby/index.jsx
web/src/views/ModelPrice/index.jsx
web/src/views/Pricing/index.jsx
web/src/views/Redemption/index.jsx
web/src/views/Task/index.jsx
web/src/views/Telegram/index.jsx
web/src/views/Token/index.jsx
web/src/views/User/index.jsx
web/src/views/UserGroup/index.jsx

- 新增 InviteCard 组件，用于显示邀请链接和处理邀请逻辑
- 新增 QuotaLogWeek 组件，用于展示近七日的消费日志
- 更新 Dashboard 页面，集成新组件
- 调整页面布局和样式，优化用户体验
- 修复oidc是否启用的设置参数初始化问题
close: #586
close: #614

feat(UI):相关样式修改优化顺便修复oidc配置问题

---

web/src/i18n/locales/zh_CN.json
web/src/views/Dashboard/component/QuotaLogWeek.jsx
web/src/views/Dashboard/component/StatisticalLineChartCard.jsx
web/src/views/Dashboard/index.jsx
web/src/views/ModelPrice/index.jsx

- 在 Dashboard 页面中为统计图表卡片添加固定高度
- 重构 ModelPrice 页面中的用户组选择组件布局和

refactor(web): 优化首页和模型价格页面展示效果

---

web/src/views/Dashboard/component/QuickStartCard.jsx

- 引入 getChatLinks 函数替代直接解析 siteInfo.chat_links
- 优化聊天链接获取逻辑，提高代码复用性和可维护性

refactor(web): 优化获取聊天链接方法

---

web/src/ui-component/DateRangePicker.jsx
web/src/views/Analytics/component/Overview.jsx
web/src/views/Channel/index.jsx
web/src/views/Log/index.jsx
web/src/views/Midjourney/index.jsx
web/src/views/ModelOwnedby/index.jsx
web/src/views/Redemption/index.jsx
web/src/views/Task/index.jsx
web/src/views/Telegram/index.jsx
web/src/views/Token/index.jsx
web/src/views/User/index.jsx
web/src/views/UserGroup/index.jsx

fix(UI):修复一些UI体验问题

---

web/src/views/Analytics/component/Statistics.jsx

-调整了渠道统计信息的布局，使用换行符分隔不同的统计项
-修复了禁用渠道数量展示的问题，确保数据展示更加准确

refactor(web): 优化渠道统计信息的展示格式

---

providers/ali/chat.go
providers/ali/model.go

feat(model): 优化ali支持websearch模型的处理逻辑

---

web/src/layout/MainLayout/ProfileDrawer/index.jsx

- 在用户组信息中添加了新的显示字段
- 修改了 API 调用速率的显示方式
- 增加了未知值的处理

feat(web): 更新用户组信息显示

---

common/limit/api_limiter.go
common/limit/countgetscript.lua
common/limit/countlimit.go
common/limit/limiter.go
common/limit/tokengetscript.lua
common/limit/tokenlimit.go
controller/user.go
router/api-router.go
web/src/i18n/locales/en_US.json
web/src/i18n/locales/ja_JP.json
web/src/i18n/locales/zh_CN.json
web/src/i18n/locales/zh_HK.json
web/src/views/Dashboard/component/RPM.jsx
web/src/views/Dashboard/index.jsx

- 在用户仪表盘添加 RPM（每分钟请求率）实时监控卡片
- 新增 API接口获取用户实时速率使用情况
- 优化限流器实现，增加获取当前速率的方法
- 更新国际化文件，添加新的速率监控相关翻译

feat(dashboard): 添加实时速率监控功能

---

docs/use/prices_update.md

添加一下价格源的供应商信息

---

web/src/i18n/locales/en_US.json
web/src/i18n/locales/ja_JP.json
web/src/i18n/locales/zh_CN.json
web/src/i18n/locales/zh_HK.json
web/src/layout/MainLayout/Sidebar/MenuCard/index.jsx
web/src/views/Dashboard/component/ModelUsagePieChart.jsx
web/src/views/Dashboard/index.jsx

侧边栏信息显示和dashboard的"近七日模型使用情况"

---

controller/user.go
router/api-router.go
web/src/i18n/locales/zh_CN.json
web/src/utils/common.jsx
web/src/views/Invoice/component/TableRow.jsx
web/src/views/Invoice/detail.jsx
web/src/views/Setting/component/OperationSetting.jsx

feat(OperationSetting): 增加账单手动生成功能

---

model/main.go
model/statistics_month.go

- 修改StatisticsMonthGeneratedHistory表中date字段类型为date以确保正确性
- 增加UserInvoiceMonth配置下的条件性表迁移逻辑，提升灵活性

fix(Model): 修复日期格式及条件性表迁移逻辑

---

model/statistics_month.go
web/src/views/Invoice/index.jsx

修复查询用户发票分页时未正确统计总数的问题，同时新增日志记录用于定位错误，提升代码可靠性。

fix(statistics_month): 修复分页统计总数查询错误并优化日志记录

---

web/src/layout/MainLayout/ProfileDrawer/index.jsx
web/src/layout/MainLayout/Sidebar/MenuCard/index.jsx

- 修改ProfileDrawer中unknown的默认值为国际化文本，提升一致性
- 注释MenuCard中未使用的图标代码，并优化RPM文字格式统一化
- 提升UI展示的合理性与代码可读性

style(ProfileDrawer, MenuCard): 修复默认值显示问题与样式优化

---

controller/invoice.go
model/statistics_month.go
router/api-router.go
web/src/i18n/locales/zh_CN.json
web/src/views/Setting/component/OperationSetting.jsx

新增控制器、路由及界面逻辑以支持更新月账单功能。优化账单生成流程，并改进生成逻辑防止数据重复生成。
- 增加了 UpdateInvoice 控制器来处理更新请求
- 前端添加“更新月账单”按钮及对应功能
- 优化 IsStatisticsMonthGenerated 用法以提高重复性校验效率

feat(invoice): 增加更新月账单功能

---

controller/invoice.go

- 更正了`invoiceTime`与当前月份比较的逻辑，避免错误判断。
- 对变量名进行了改进以提升可读性。

fix(invoice): 修正时间比较逻辑错误

---

web/src/assets/css/content-viewer.css
web/src/ui-component/ContentViewer.jsx
web/src/views/About/index.jsx
web/src/views/Home/index.jsx

新增ContentViewer组件，用于处理Markdown、HTML及URL内容展示，并应用到Home和About页面。移除原有的marked解析逻辑。让首页和关于页面自定义内容支持完整的HTML内容
- 支持Markdown到HTML的转换及URL嵌入显示
- 提供加载状态和错误提示的处理能力
- 优化代码复用性及页面组件结构
```
<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SuperAI - 最先进的AI聚合平台</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap">
<style>
:root {
--primary: #3b82f6;
--primary-light: #93c5fd;
--secondary: #10b981;
--secondary-light: #6ee7b7;
--dark: #111827;
--gray: #4b5563;
--light-gray: #9ca3af;
--lighter-gray: #f3f4f6;
--white: #ffffff;
--bg: #ffffff;
--card-bg: #ffffff;
--card-hover: #f9fafb;
}
* {
margin: …
```

feat(ContentViewer): 添加Markdown/HTML内容展示组件并集成到Home与About页面

---

mcp/tools/current_time/current_time.go
mcp/tools/dashboard/dashboard.go

简化Dashboard和CurrentTime工具的初始化过程，
采用protocol.NewTool减少代码冗余。
- 修改了Dashboard工具的GetTool方法
- 修改了CurrentTime工具的GetTool方法

fix(mcp): 修复git错误提交导致代码混乱问题

---

providers/azure/base.go
providers/azure/model.go

- 调整了AZURE获取模型ID处理逻辑，保留原始ID数据不再去掉点；
- 新增Azure对图片编辑和变体功能的路径支持。

feat(azure): 更新模型列表处理及新增图片编辑与变体支持

---

providers/ali/chat.go
providers/ali/type.go
types/chat.go

新增字段EnableThinking，作为qwen3的思考开关配置。
- 更新了types/chat.go文件
- 保持向后兼容性

feat(types): 添加启用思考的开关字段

---

web/src/themes/index.js

更新主题中的背景颜色代码以改进样式一致性和视觉一致性。
- 调整 `backgroundDefault` 和 `background` 的值
- 修改表头背景色及悬停状态的颜色

style(theme): 调整背景颜色以提升一致性

---

common/common.go
controller/order.go
controller/user.go
model/log.go
model/redemption.go
web/src/layout/MainLayout/Sidebar/MenuCard/index.jsx
web/src/utils/common.jsx
web/src/views/Log/component/TableRow.jsx

- 新增RecordQuotaLog函数，增强日志记录功能以支持记录配额变化。
- 在多处代码中替换旧的RecordLog调用为新的RecordQuotaLog。
- 改进配额显示逻辑，支持负值配额显示为负金额格式。
- 修复部分UI中配额展示格式问题，提升用户体验。

feat(log): 优化日志记录与配额展示逻辑

---

providers/bedrock/category/base.go

新增Claude-3-7 model ID的映射，包括us、eu、apac区域。

feat(category): 新增支持Claude-3-7相关模型映射

---

README.md

新增以下支持功能的说明：
- `Uptime Kuma`状态监控
- 用户分组自动升级
- 用户月度账单生成
- 多策略模型价格自动更新
- `Gemini`与`Claude`格式的API请求
详见README文档更新以了解更多细节。

feat(docs): 更新README以新增功能说明

---

web/src/views/SystemInfo/components/SystemLogs.jsx

重构 `fetchLogs` 函数并使用 `useCallback`，减少不必要的重渲染次数。
调整 `useEffect` 生命周期以更明确地管理日志获取及自动刷新逻辑。
- 使用 `useCallback` 优化日志获取。
- 添加组件挂载时的初始日志获取逻辑。
- 分离 `maxEntries` 和 `autoRefresh` 改变时的处理流程。
简化代码并提高运行效率，避免不必要的 API 调用或渲染。

refactor(system-logs): 优化日志获取逻辑以提高组件性能

---

docs/use/special.md
providers/gemini/chat.go
providers/gemini/type.go

close #714
另外因为现在google search允许和另外两个tool共存，所以移除了判断len的逻辑。
我已确认该 PR 已自测通过

feat(gemini): support urlContext

---

middleware/logger.go
relay/model.go
router/relay-router.go
web/src/layout/MainLayout/Header/Profile/index.jsx
web/src/layout/MainLayout/Sidebar/MenuCard/index.jsx
web/src/layout/MainLayout/Sidebar/MenuList/NavItem/index.jsx
web/src/themes/typography.js
web/src/ui-component/ThemeButton.jsx
web/src/ui-component/cards/MainCard.jsx
web/src/ui-component/cards/UserCard.jsx
web/src/ui-component/i18nButton.jsx
web/src/ui-component/notice/NoticeButton.jsx
web/src/views/SystemInfo/components/SystemLogs.jsx

- 前端部分调整
新增两个功能：
- Claude模型分组查询接口 (/claude/v1/models)
- Gemini模型分组查询接口 (/gemini/:version/models)
增强了对不同模型分组的支持，并优化了查询逻辑。

feat(relay): 增加Claude和Gemini模型列表接口

---

web/src/views/Log/component/QuotaWithDetailContent.jsx
web/src/views/Log/component/QuotaWithDetailRow.jsx
web/src/views/Log/component/TableRow.jsx
web/src/views/Log/component/TableToolBar.jsx

Introduced an expandable row to display detailed quota information, including original and actual pricing, group ratio, and calculation breakdown. Refactored price calculation logic for clarity and reusability. Updated `TableRow` component to integrate new features.

feat(log-table): add expandable quota details and refactor price calculation

---

web/src/views/Pricing/component/EditModal.jsx

[pull#741](https://github.com/MartialBE/one-hub/pull/741)

fix: model price edit 修复新建模型价格后无法再次编辑 类型 与 渠道类型 的bug

---

providers/gemini/type.go

Revert "feat: 兼容Gemini的思考对齐openai响应"

---

providers/base/interface.go
providers/openai/base.go
relay/common.go
relay/main.go

close #712
在额外参数上添加了一个pre_add，如果设置为true，则在接收时就提前进行参数替换，而不是在发送时进行参数替换。因为是在接收侧实现，所以兼容包括gemini在内的所有渠道。
例：
```json
{
"pre_add": true,
"overwrite": true,
"stream": false,
"reasoning": {
"max_tokens": 0
},
"tools": []
}
```
```bash
$ curl http://localhost:13333/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $SELF_API_KEY" \
-d '{
"model": "gemini-2.5-flash",
"stream": false,
"tools": [{"type": "function", "function": {"name": "googleSearch"}}],
"messages": [
{
"role": "user",
"content": "今天北京天气"
}
]
}'
{"id":"chatcmpl-80b8959fcf7a45f3ac73b5a4c3cb6b24","object":"chat.completion","created":1749393430,"model":"gemini-2.5-flash-preview-05-20","choices":[{"index":0,"message":{"role":"assistant","content":"您好，北京今天的天气情况是：\n\n* **气温：** 19°C / 9°C\n* **天气现象：** …
```

feat(channel): global pre_add in custom params

---

router/web-router.go

移除了`EmbedFolder`函数的错误处理逻辑，直接返回嵌入文件系统对象。优化后的代码减少了不必要的错误判断，提升了可读性和维护性。

refactor(router): 简化适配低版本gin嵌入文件系统的初始化逻辑

---

common/config/constants.go
providers/azuredatabricks/main.go
providers/providers.go

close #772
我已确认该 PR 已自测通过
链接填写如 `https://adb-XXXXXXXXXXXXXXX.XX.azuredatabricks.net` 的基础域名，模型名填写如 `databricks-claude-sonnet-4`, key填 `DATABRICKS_TOKEN` 即可。

feat: support azure databricks

---

web/src/views/Channel/component/EditModal.jsx

refactor(Channel/EditModal): 将批量添加开关移至密钥输入框的提示文本旁
