common/model-ratio.go
更新 
向量模型：
- `text-embedding-3-small ` / `text-embedding-3-large` 
语言模型： 
- `gpt-4-0125-preview` / `gpt-4-preview`  （`gpt-4-preview` 是 指向最新版本的 `gpt4` preview版本),
- `gpt-3.5-turbo-0125` (暂时不可用，等待下周正式发布)
=> ✨ feat: update openai new model

i18n/en.json, middleware/auth.go, providers/base/common.go, providers/base/interface.go, providers/openai/base.go, relay/common.go, relay/main.go, relay/relay.go, router/relay-router.go
1. 支持`fine-tuning`/`files`/`batches`/`assistants`等接口
2. 仅限超级管理员使用
3. 无计费
4. 必须是`OpenAI`或者`Azure OpenAI`渠道， 推荐`OpenAI`，因为`Azure OpenAI`支持不完整。
必须在令牌中指定你需要使用的渠道 例如：`sk-{your token}-{channel id}`
因为指定渠道后，那么其他供应商的聊天模型是无法使用的，所以提供了`ignore`关键字的方法。
将令牌改为：`sk-{your token}-{channel id}-ignore` 即可开启。
开启`ignore`后，除了`OpenAI`特有的接口以外，其他接口都会忽略`指定渠道ID`，可以使用负载均衡，使用支持的其他供应商模型。
- /completions
- /chat/completions
- /images/generations
- /images/edits
- /images/variations
- /embeddings
- /audio/transcriptions
- /audio/translations
- /audio/speech
- /moderations
- /files*
- /fine_tuning*
- /assistants*
- /threads*
- /batches*
- /vector_stores*
- DEL /models/*
=> ✨ feat: support other OpenAI APIs

common/storage/drives/alioss.go, common/storage/storage.go, common/storage/storage_test.go, config.example.yaml, go.mod, go.sum
feat(图床增加阿里OSS支持): 
STORAGE_ALIOSS_ENDPOINT：Endpoint（地域节点）,比如`oss-cn-beijing.aliyuncs.com`
STORAGE_ALIOSS_BUCKET_NAME：Bucket名称，比如`zerodeng-superai`
STORAGE_ALIOSS_ACCESS_KEY_ID：阿里授权KEY,在RAM获取
STORAGE_ALIOSS_ACCESS_KEY_SECRET：阿里授权SECRET,在RAM获取
=> ✨ feat: add AliOSS image upload

payment/gateway/alipay/payment.go, web/src/views/Payment/type/Config.js
=> 🐛fix: aliPay missing parameters

web/src/views/Topup/component/PayDialog.js
支付宝扫码支付弹窗增加打开支付宝按钮，手机端点击按钮可以直接拉起支付宝进行支付。
=> 🔖 chore: Alipay QR code payment add open Alipay button

payment/gateway/alipay/client.go, payment/gateway/alipay/payment.go, payment/gateway/alipay/type.go, web/src/views/Payment/type/Config.js
增加wap网页支付方式；优化代码结构，把支付方式处理单独拆分导`client.go`；
- wap和pc网页支付需要有密钥权限的用户进行实际测试
=> 🔖 chore: Alipay adds WAP payment

prices.json
price.json 中 minimax 的 abab6.5-chat 和 abab6.5s-chat，价格搞反了，前者价格是后者三倍，分别对于倍率应该是 abab6.5-chat ：2.1429 ，abab6.5s-chat：0.7143
见官方文档：https://platform.minimaxi.com/document/price?id=6433f32294878d408fc8293e
我已确认该 PR 已自测通过
=> fix: correct  prices of abab6.5-chat & abab6.5s-chat

prices.json
恭喜 yi-lightning 登顶 lmsys 第六
更新下 01-AI 的模型和价格，参照：https://platform.lingyiwanwu.com/docs#%E6%A8%A1%E5%9E%8B%E4%B8%8E%E8%AE%A1%E8%B4%B9
Additions to `prices.json`:
=> Update prices.json with 01 AI

go.mod, go.sum, payment/gateway/stripe/payment.go
升级 `stripe-go` 版本以满足 webhook 更新需求。
Related: #370 
=> fix: upgrade stripe-go version

providers/bedrock/category/base.go
增加aws bedrock Claude Cross-region模型支持。
参考资料：https://docs.aws.amazon.com/bedrock/latest/userguide/inference-profiles-support.html
实现和配置方式：
类似`US Anthropic Claude 3 Sonnet`的Inference profile ID是`us.anthropic.claude-3-sonnet-20240229-v1:0`,后端做对应适配。在配置渠道模型的时候在原有模型名字前面以`.`分割增加区域标记us，即US Anthropic Claude 3 Sonnet的模型配置应该配置为`us.claude-3-5-sonnet-20240620`,如下图：
如果需要用户请求claude-3-5-sonnet-20240620可以访问onehub的对应模型可以使用模型映射功能。
close #415
=> 增加aws bedrock Claude Cross-region模型支持

web/src/i18n/locales/en_US.json, web/src/i18n/locales/ja_JP.json, web/src/i18n/locales/zh_CN.json, web/src/i18n/locales/zh_HK.json, web/src/layout/MainLayout/Header/index.jsx, web/src/layout/MinimalLayout/Header/index.jsx, web/src/menu-items/dashboard.jsx, web/src/ui-component/NoticeButton.jsx
1. playground改成国人熟知的“聊天”，这样更加符合目前该模块的功能属性定义
2. 增加通知重复查看按钮和功能，防止手滑关掉通知后再也找不到通知内容了
=> Notice & i18n

web/src/i18n/locales/en_US.json, web/src/i18n/locales/ja_JP.json, web/src/i18n/locales/zh_CN.json, web/src/i18n/locales/zh_HK.json, web/src/views/Channel/component/EditModal.jsx
创建渠道的弹窗，自定义参数太多了而且不常用，每次要多滚动一屏；改为默认收起自定义参数部分的内容，可以手动展开
=> chore: 编辑渠道弹窗默认收起自定义参数

providers/siliconflow/main.go
修改siliconflow api URL为api.siliconflow.com。根据硅基流动支持群消息，此url会根据请求源ip自动导向更快的服务器。已向官方确认已确认可用。
=> use auto routing URL according to siliconflow support team

web/src/views/Authentication/AuthForms/WechatModal.jsx
该 PR 主要修复通过微信扫码登录过程中，不管成功还是失败，都会有一个未知错误的提示，并且失败的话，没有提示具体的失败原因：
登录成功的场景也是正常的。
=> fix: 修复微信登录的报错信息提示不正确的问题

Dockerfile
close #474 
Dockerfile 没有拷贝lock文件，导致依赖跳版本构建报错
修改Dockerfile前：
修改后：
=> fix: 首次通过 dockerfile 构建可能会报错

web/src/i18n/locales/zh_CN.json, web/src/ui-component/ToggleButton.jsx, web/src/views/ModelPrice/index.jsx, web/src/views/Pricing/component/EditModal.jsx
增加每K价格到倍率的自动换算功能，新增模型价格的时候可以输入每K的价格（美元）自动换算成系统倍率。
=> feat(模型价格新增): 优化价格配置功能

web/src/views/Pricing/component/EditModal.jsx, web/src/views/Pricing/component/util.js
1. 修复模型价格增删面板当选择计算方式为法币时输入框为空崩溃的问题。
2. 一些简单体验的调整优化
=> fix(模型价格): 修复模型价格增删页面崩溃问题

web/src/views/Token/index.jsx
后端实际已经对 API 能够获取到的用户组进行了筛选，只会返回用户当前用户组或者公开用户组，前端再次筛选会导致用户看不到非公开但是自己有权限的用户组
```go
// controller/group.go:26
UserGroup := make(map[string]*model.UserGroup)
for k, v := range groupRatio {
if v.Public || k == userSymbol {
UserGroup[k] = v
}
}
```
=> fix(user): remove user group filter

providers/github/base.go, web/src/views/Channel/type/Config.js
The baseURL for GitHub Model has been changed to "https://models.github.ai/inference"
=> Update default baseURL for Github Model

web/src/i18n/locales/en_US.json, web/src/i18n/locales/ja_JP.json, web/src/i18n/locales/zh_CN.json, web/src/i18n/locales/zh_HK.json, web/src/views/Log/component/TableRow.jsx
优化日志详情显示方式
- 对于0费记录在详情显示免费标记而不是展示0费费率
- 对于非0费记录的老版本记录做单独展示
=> style(日志): 优化日志显示

providers/gemini/relay.go, providers/gemini/type.go, providers/siliconflow/main.go, web/src/views/Channel/type/Config.js
Gemini渠道`content`里的`parts`可能不存在，比如最后STOP的时候就没有`parts`，所以需要单独判断parts有没有子集然后再取子集
=> fix(Gemini): Gemini代理异常解决

providers/openai/image_generations.go, relay/image-generations.go
解决了 OpenAI 格式图像生成 API，当模型名称不是 dall-e-2 或 dall-e-3 时无法正常使用的问题。
close #565
=> 解决了 OpenAI 格式图像生成 API，当模型名称不是 dall-e-2 或 dall-e-3 时无法正常使用的问题。

web/src/views/Channel/component/TableRow.jsx
原来：
现在：
使得“可用模型”标签与“测速模型”标签以及仪表盘“当前可用模型”标签的样式保持一致。
=> 使可用模型标签的UI与整体一致

.cursorignore, web/src/constants/CommonConstants.js, web/src/views/Channel/component/ChannelTable.jsx, web/src/views/Channel/index.jsx, web/src/views/Log/index.jsx, web/src/views/Midjourney/index.jsx, web/src/views/Payment/Gateway.jsx, web/src/views/Payment/Order.jsx, web/src/views/Pricing/single.jsx, web/src/views/Redemption/index.jsx, web/src/views/Task/index.jsx, web/src/views/Telegram/index.jsx, web/src/views/Token/index.jsx, web/src/views/User/index.jsx, web/src/views/UserGroup/index.jsx
- 在 CommonConstants.js 中新增 getPageSize 和 savePageSize 函数，用于管理页面大小的本地存储。
- 更新多个视图组件，使用 getPageSize 函数初始化每页行数，并在行数变化时调用 savePageSize 保存设置。
- 确保用户在不同页面间切换时，能够保持自定义的页面大小设置。
close [#539](https://github.com/MartialBE/one-hub/issues/539)
=> 添加页面大小管理功能，支持从 localStorage 获取和保存页面大小

controller/oidc.go, model/user.go, web/src/views/Profile/index.jsx
- 新增 OIDC 认证流程，包括授权码验证、ID Token 解析和用户信息获取
- 实现通过 OIDC ID 和用户名查询用户的功能- 添加新用户注册逻辑，支持通过 OIDC 创建新账户
- 在用户模型中增加 OIDC ID 字段并添加相关查询方法- 更新用户界面，在个人资料页面添加 OIDC 账号绑定显示
=> feat(auth): 添加 OIDC ID 认证支持，防止用户修改OIDC平台USERNAME而无法进行认证。

web/src/views/Channel/component/TableRow.jsx
=> 标签渠道列表里的分页行数支持记忆能力

web/src/views/Dashboard/component/QuickStartCard.jsx
- 修复了 chatLinks 可能为 null 导致的解析错误
- 优化了聊天链接的判断条件，确保仅在存在链接时显示
=> fix(Dashboard): 修复快速开始卡片的聊天链接显示逻辑

web/src/views/Dashboard/component/QuickStartCard.jsx
- 移除了不必要的 initChatOptions 函数，简化了代码结构
- 新增 getProcessedUrl 函数，用于生成处理后的聊天链接
- 优化了 handleClick 方法，使用新的 getProcessedUrl 函数处理聊天链接
- 删除了未使用的 newQuickStartOptions 和 newLocalOptions 数组
=> refactor(Dashboard): 优化 QuickStartCard 组件中的聊天链接处理逻辑只有点击按钮才生成默认key

web/src/layout/MainLayout/ProfileDrawer/index.jsx
- 将 'modelpricePage.rate'替换为 'modelpricePage.RPM'，统一显示文案
- 保留 API 速率的数值不变
=> refactor(web): 优化用户组 API 速率显示文案

model/option.go
- 将配置项名称从 "DisableChannelKeywordsDisableChannelKeywords" 修改为 "DisableChannelKeywords"
=> fix(model): 修复禁用频道关键词配置项名称重复问题

common/limit/api_limiter.go
- 将 API 限流窗口时间从变量 window 修改为 1 秒
- 确保限流器以每秒为单位进行计数
=> fix(common): 修复 API 限流窗口时间设置错误

common/limit/api_limiter.go, common/limit/slidingwindow.go, common/limit/slidingwindow.lua, common/limit/slidingwindowget.lua
- 临时增加滑动窗口用于高RPM场景（比较好的方式还是令牌桶，但是令牌桶无法直接准确获取RPM）
- 简化为直接使用 RPM 作为参数调用 NewCountLimiter
- 保留原有的代码结构，以备将来可能的恢复
=> refactor(common): 修改 limiter 函数逻辑

common/limit/api_limiter.go, common/limit/countlimit.go, common/limit/slidingwindow.go, common/limit/tokengetscript.lua, common/limit/tokenlimit.go, common/limit/tokenscript.lua
- 新增计数器逻辑，记录每个请求的 RPM- 在 tokengetscript.lua 和 tokenscript.lua 中添加 RPM 相关的处理
- 修改 TokenLimiter 结构，增加 rpm 字段- 更新 GetCurrentRate 方法，返回实时 RPM
- 调整 reserveN 方法，处理 RPM 限制这个改动实现了在 token bucket 限流器中记录和返回实时 RPM 的功能，以便更准确地监控和控制 API 调用速率。
【模拟并发测试100~500毫秒请求间隔还是令牌桶的方案比较合适，滑动窗口方案在突发情况或者窗口多的情况不理想】
=> feat(limit): 实现 token bucket限流器的实时 RPM 统计

common/config/config.go, common/config/constants.go, config.example.yaml, controller/github.go, model/option.go
- 新增配置项github_proxy，使GitHub登录请求支持通过HTTP/HTTPS/SOCKS5代理发送，提升灵活性和适配性。
- 修复github登录失败问题
=> fix(GitHub): 修复github登录失败问题

controller/invoice.go
- 修复发票时间验证错误，更新逻辑为不允许发票时间大于等于当前月份。
- 调整 `InsertStatisticsMonthForDate` 调用参数，提升时间计算的可靠性和一致性。
=> fix(controller): 修复发票时间验证逻辑问题

types/chat.go
考虑支持更多模型使用OpenAI API格式扩展参数，新增以下可选参数：
- thinking_budget: qwen3的思考长度，需启用enable_thinking
- enable_search: qwen的搜索开关
=> feat(types): 增加思考预算和搜索开关支持

common/config/config.go, common/config/constants.go, config.example.yaml, controller/misc.go, controller/uptime_kuma.go, router/api-router.go, web/src/config.js, web/src/i18n/locales/zh_CN.json, web/src/layout/MinimalLayout/Header/index.jsx, web/src/views/Dashboard/component/StatusPanel.jsx, web/src/views/Dashboard/index.jsx, web/src/views/Log/index.jsx, web/vite.config.mjs
新增对Uptime Kuma状态展示的支持，包括状态页面和心跳数据的集成，以及前端和后端的相关组件与配置。
- 在仪表盘新增状态面板Tab，用于展示Uptime Kuma数据。
- 后端增加状态页面和心跳数据接口。
- 新增配置选项以支持Uptime Kuma相关功能。
具体使用详见配置文件：
```
uptime_kuma:
enable: false # 是否开启uptime kuma状态展示
domain: ""     # uptime-kuma项目地址 例如https://status.xxxxx.com
status_page_name: "" #  uptime-kuma状态页面slug
```
=> feat(dashboard): 增加uptime kuma状态监控面板

web/src/views/Pricing/component/EditModal.jsx
> 新增模型价格后再次编辑价格时string未转换number。
before:
after:
=> fix: input/output format - 修复编辑模型价格input/output字段类型字符串的问题

providers/github/base.go, providers/github/model.go, providers/github/type.go, web/src/views/Channel/type/Config.js
新增通过Github获取模型列表的功能，包括相关的请求逻辑和数据结构。
- 添加GetModelList方法，用于发送HTTP请求获取模型列表
- 定义ModelListResponse及ModelInfo数据结构
- 更新GithubProvider配置，新增ModelList字段
- 修改前端配置，支持展示Github提供的模型列表标签
=> feat(github-provider): 实现获取模型列表功能

web/src/i18n/locales/en_US.json, web/src/i18n/locales/zh_CN.json, web/src/views/Channel/component/EditModal.jsx, web/src/views/Channel/component/ModelSelectorModal.jsx
- 在`en_US.json`和`zh_CN.json`中添加了多个新翻译项，包括“转换为小写”、“覆盖模型列表”、“重置”等。
- 在`EditModal.jsx`和`ModelSelectorModal.jsx`中实现了模型选择器的覆盖和追加模式功能，支持用户选择模型时的不同操作方式。
- 增加了相关的提示信息和功能开关，以提升用户体验和操作灵活性。
1. 支持在模型选择器重置所有已选模型
2. 支持直接覆盖编辑框里选择的模型列表
3. 支持在设置模型映射时：模型名称转小写
4. 支持在设置模型映射时：不填充映射前的模型名称
5. 支持在设置模型映射时：覆盖编辑器中原有映射关系
=> feat: 模型选择器功能完善

relay/model.go
Updated the model name formatting to include a "models/" prefix in the Gemini channel type assignment.
=> fix(relay): correct model name formatting in Gemini channel

common/limit/countlimit.go, common/limit/slidingwindow.go, common/limit/tokenlimit.go
修复API限速器在Redis未配置情况下获取实时速率的问题。添加Redis配置检查逻辑并更新速率获取方法。
- 针对CountLimiter、SlidingWindowLimiter和TokenLimiter增加RedisEnabled判断
- 提供明确的错误提示，提高问题诊断效率
=> fix(limit): 检查Redis配置以避免获取实时RPM时出错

main.go
- 配置了session存储选项，支持设置路径、有效期等参数。
- 支持HttpOnly、Secure及SameSite选项用于增强会话安全性。
提升了会话管理的灵活性和安全性。
close #757
=> fix(session): 增加会话存储选项配置支持

providers/gemini/type.go, relay/model.go
- 新增`DisplayName`字段，使用标题化处理为模型名称生成更友好的显示名称。
- 引入`golang.org/x/text/cases`与`strings.ReplaceAll`库，用于名称格式化。
- 优化Gemini模型详细信息构建逻辑，提高可读性和易用性。
此更新旨在改善用户界面模型名称的显示效果。
=> feat(relay): 增加Gemini Model显示名称支持

web/src/views/ModelPrice/index.jsx
=> style(web): 调整ModelPrice页面“供应商”的对齐方式

web/src/views/Channel/component/TableRow.jsx
=> style(Channel/TableRow): 移除多余的maxWidth样式属性

web/src/themes/compStyleOverride.js, web/src/ui-component/IconWrapper.jsx
=> style: 移除多余的padding样式属性，并居中图标

controller/webauthn.go, router/api-router.go
- 为WebAuthn登录接口`/login/begin`和`/login/finish`增加关键限流中间件，提高安全性及防御能力。
- 统一登录错误提示为“登陆失败”，避免泄露过多内部信息并改进用户体验。
=> fix(webauthn): 增强登录接口限流及优化错误信息

model/user.go
- 将`CredentialId`字段类型更改为字节数组，移除Base64编码环节以优化存储与处理。
- 更新相关接口逻辑以兼容字段类型调整。
=> fix(webauthn): 更新凭据ID字段类型为字节数组并简化编码逻辑,多数据类型兼容
